import Head from "next/head";
import Banners from "../components/home/Banners";
import Hero from "../components/home/Hero";
import ProductsInToday from "../components/home/ProductsInToday";
import Selected from "../components/home/Selected";
import WhyChooseUs from "../components/home/WhyChooseUs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Banners />
      <Selected />
      <WhyChooseUs />
      <ProductsInToday />
    </div>
  );
}
